src/checktime/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('index/',include('time_clock.urls')),
    path('',include('time_clock.urls')),
    path('user/',include('user.urls'))
]

src/time_clock/urls.py
from django.urls import path
from . import views

app_name = 'time_clock'

urlpatterns = [
    path('', views.UserActivity_View.as_view(),name='index'),
    path('history/', views.UserActivity_ListView.as_view(),name='history'),
    path('history/<datetype>/', views.UserActivity_ListView.as_view(),name='history-type')
]

src/user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('login/', views.Login_View.as_view(),name='login'),
    path('signup/', views.Signup_View.as_view(),name='signup'),
    path('logout/', views.auth_logout,name='logout')
]

src/time_clock/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import datetime,time,timedelta
from django.conf import settings
# from django.contrib import messages
# from django.utils import timezone
# Create your models here.
# User activity
# 获取延迟时间
get_activity_timedelta = getattr(settings,'TIME_DELTA_MIN',1)
get_pass_checkin = getattr(settings,'PASS_CHECKIN',True)
get_check_intoday = getattr(settings,'CHECK_IN_TODAY',False)
def instance_type(**kwargs):
    for key,value in kwargs.items():
        if key == 'TIME_DELTA_MIN' and not isinstance(value,int):
            raise TypeError("The param %s should be %s,but it's %s now!"%(key,'int',type(value)))
        if key == 'PASS_CHECKIN' and not isinstance(value,bool):
            raise TypeError("The param %s should be %s,but it's %s now!"%(key,'bool',type(value)))
        if key == 'CHECK_IN_TODAY' and not isinstance(value,bool):
            raise TypeError("The param %s should be %s,but it's %s now!"%(key,'bool',type(value)))    
instance_type(
            TIME_DELTA_MIN=get_activity_timedelta,
            PASS_CHECKIN=get_pass_checkin,
            CHECK_IN_TODAY=get_check_intoday)

USER_ACTIVITY_CHOICES =[
    ('checkin','签到'),
    ('checkout','签出')
]
class UserActivityQuerySet(models.query.QuerySet):
    '''
    模型查询集:自定义查询集
    '''
    def filter_date(self,*args,**kwagrs):
        '''
        days=0 filter today
        days=1 filter yesterday
        days=-1 filter yesterday
        if days = +-2 filter within 2 days  ex.days=7 filter within a week
        '''
        # print(args,kwagrs)
        days = kwagrs.get('days',None)
        if days is None:
            raise TypeError('filter_date() takes 1 keywords arguments:days')
        if days < 0 :
            days =  -days
        days_delta = timedelta(days=days) #时间轴
        now_date = timezone.localdate() #　当天的日期
        start_date = now_date - days_delta # 起始日
        # print('可选日期：',start_date)
        datetime_start = timezone.make_aware(datetime.combine(start_date,time.min))# 起始时间
        datetime_end = timezone.make_aware(datetime.combine(start_date,time.max))
        if days >=2 : # 范围内可选
            datetime_end = timezone.make_aware(datetime.combine(now_date,time.max))
        return self.filter(timestamp__gte=datetime_start).filter(timestamp__lte=datetime_end)
    def current_set(self,user=None):
        if user is None:
            return None
        current = self.filter(user=user).order_by('-timestamp').first()
        return current
class UserActivityManager(models.Manager):
    '''
    模型管理器:自定义模型对象操作，例如查询和保存
    '''
    def get_queryset(self,*args,**kwagrs):
        return UserActivityQuerySet(self.model,using=self._db)
    def current(self,user=None):
        if user == None:
            return None
        current_obj = self.get_queryset().current_set(user=user)
        return current_obj
    def toggle(self,user=None):
        if user == None:
            return None
        # 检测今天是否已经签到
        check_in_today = get_check_intoday # True表示今日签出不给再签到
        today_queryset = self.today(user=user)
        msg = 'You have been checked out in this day'
        # 初始上次对象的活动
        get_current_activity = None
        # 默认动作
        action_activity = 'checkin'
        # 起始计数
        init_count = 1
        get_current = self.current(user=user)   
        if get_current:
            # 上次对象的活动类型
            get_current_activity = get_current.activity
            # 上次对象的活动计数
            get_current_activity_count = get_current.activity_count
            # 计数加一
            next_count = get_current_activity_count + 1 
        if get_current_activity == 'checkin':
            action_activity = 'checkout'
        if today_queryset.exists() and today_queryset.first().activity == 'checkout' and check_in_today:
            return msg
        
        new_obj = self.model(user=user,
                            activity=action_activity,
                            activity_count=next_count if get_current else init_count)
        new_obj.save()
        return new_obj
    def checkout_dely_toggle(self,user=None):
        pass_checkin = get_pass_checkin # True不需要延迟
        recent_obj = self.current(user=user)
        if recent_obj != None:
            recent_obj_timestamp = recent_obj.timestamp
            delta = timedelta(minutes=get_activity_timedelta)
            # 下次action 时间
            action_time = recent_obj_timestamp + delta
            now = timezone.now()
            diff_time = action_time - now
            if recent_obj.activity == 'checkout' and pass_checkin :
                return self.toggle(user=user)
            if now < action_time:
                # print('{:.1f}分钟'.format(diff_time.seconds/60))
                diff_time_shift = '{:.0f}秒'.format(diff_time.seconds)
                msg = 'Must wait {time}'.format(time=diff_time_shift)
                return msg
            # return self.toggle(user=user)
        return self.toggle(user=user)
    # 日期范围快捷函数
    def get_daterange(self,days=0,user=None):
        if user is None:
            return self.get_queryset().filter_date(days=days)
        return self.get_queryset().filter(user=user).filter_date(days=days)
    def today(self,days=0,user=None):
        return self.get_daterange(user=user,days=days)
    def yesterday(self,days=1,user=None):
        return self.get_daterange(user=user,days=days)
    def within_week(self,days=7,user=None):
        return self.get_daterange(user=user,days=days)
class UserActivity(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    activity = models.CharField(max_length=20,default='checkin',choices=USER_ACTIVITY_CHOICES,verbose_name='状态')
    timestamp = models.DateTimeField(auto_now_add=True,verbose_name='记录时间')
    activity_count = models.IntegerField(blank=True,verbose_name='操作次数')
    objects = UserActivityManager()
    class Meta:
        verbose_name='打卡记录'
        verbose_name_plural=verbose_name
        ordering = ['-timestamp']

    def __str__(self):
        return self.user.username

    def clean(self,*args,**kwargs):
        if self.user:
            user_activitys = UserActivity.objects.filter(user=self.user).order_by('-timestamp')    
            # print([ac.activity for ac in user_activitys])
            if user_activitys.exists():
                recent = user_activitys.first()
                # print(recent.activity)
                if self.activity == recent.activity:
                    message = '无效操作:你已经%s过' %(self.get_activity_display())
                    raise ValidationError(message)
            else:
                if self.activity != 'checkin':
                    message = '无效操作:第一次不能%s' %(self.get_activity_display())
                    raise ValidationError(message)
        return super(UserActivity,self).clean(*args,**kwargs)

    def next_activity(self):
        next = '签到'
        if self.activity == 'checkin':
            next = '签出'
        return next
    @property
    def current_activity_display(self):
        show = '签到'
        if self.activity == 'checkout':
            show = '签出'
        return show
    def today_is_checked(self,user):
        msg ='今日已经打卡了'
        today_objs = self.objects.today(user=user)
        if today_objs:
            obj_activity = today_objs.first().activity
            if  obj_activity == 'checkout':
                return msg
        return self.objects.checkout_dely_toggle(user=user)
            

src/time_clock/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()
class CheckRequired_PwForm(forms.Form):
    username = forms.CharField(widget=forms.HiddenInput)
    password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'输入密码','type':'password','required':'true'}))
    def clean(self,*args,**kwagrs):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username','')
        password = cleaned_data.get('password','')
        exist_user = User.objects.filter(username__iexact=username)
        message = '密码错误'
        # 存在这个用户但密码错误
        if exist_user.exists() and exist_user.count()==1:
            user = exist_user.first()
            check_password = user.check_password(password)
            if not check_password :
                raise forms.ValidationError(message,code='invalid')
        return cleaned_data
            
        

src/time_clock/views.py
import datetime
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib import messages
from django.contrib.auth import get_user_model
from .models import UserActivity,UserActivityManager
from django.urls import reverse
from .models import UserActivity
from django.views.generic.list import ListView
from .utils import current_page_round
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.db.models.query_utils import Q
from django.conf import settings
from .forms import CheckRequired_PwForm
from .utils import check_required_password
# from django.contrib.auth.decorators import login_required
# from django.http import HttpResponseRedirect
# from django.utils import timezone
# from datetime import timedelta,time
# Create your views here.
PER_PAGE_NUMBER = getattr(settings,'PER_PAGE_NUMBER',8)
class UserActivity_View(View):
    def get(self,request,*args,**kwargs):
        # print(request.method)
        context = {}
        recent_obj = None
        if request.user.is_authenticated:
            recent_obj = UserActivity.objects.current(user=request.user)
            context['form'] = check_required_password(request,context,CheckRequired_PwForm,recent_obj=recent_obj)
        context['recent_obj'] = recent_obj
        context['title'] = '打卡'
        
        return render(request,'time_clock/index.html',context)

    def post(self,request,*args,**kwargs):
        '''
        1.使用签出延迟请使用
        UserActivity.objects.checkout_dely_toggle(request.user)
        2.不使用延迟
        UserActivity.objects.toggle(request.user)
        '''
        context = {}
        if check_required_password(request,context,CheckRequired_PwForm):
            return render(request, 'time_clock/index.html',check_required_password(request,context,CheckRequired_PwForm))

        if request.user.is_authenticated:
            result = UserActivity.objects.checkout_dely_toggle(user=request.user)
            
            # print(result)
            if isinstance(result,str):
                messages.error(request,result)
            if isinstance(result,UserActivity):
                messages.success(request,'You Success ' + result.activity.upper())
        return redirect('time_clock:index')

class UserActivity_ListView(LoginRequiredMixin,ListView):
    login_url = '/user/login/'
    template_name = 'time_clock/history.html'
    # model = UserActivity
    context_object_name = 'user_activity_list'
    paginate_by = PER_PAGE_NUMBER if PER_PAGE_NUMBER <= 10 and PER_PAGE_NUMBER % 2 == 0  else 10
    history_type = None
    q = None
    def dispatch(self, request, *args, **kwargs):
        self.history_type = self.kwargs.get('datetype','全部')
        self.q = request.GET.get('datetime') # 搜索
        return super().dispatch(request,*args,**kwargs)
    def get_history_type(self):
        history_type = self.history_type
        if history_type == 'today':
            return '今天'   
        if history_type == 'yesterday':
            return '昨天'    
        if history_type == 'aweek':
            return '一周内'
        return history_type
    def check_q(self):
        # 搜索
        if self.q:
            try:
                queryset = []
                if self.q.find('-') == -1 or self.q.count('-') !=2 :
                    messages.error(self.request,'Search error: Format must be like year-mon-day')
                    return queryset
                check_q_format = self.q.replace('-','')
                if not check_q_format.isdigit():
                    messages.error(self.request,'Search error:only number input')
                    return queryset
                datetime_list = self.q.split('-')
                datetime_int = tuple(map(int,datetime_list)) # 改为元组
                year , mon , day = datetime_int
                queryset = UserActivity.objects.filter(user=self.request.user,timestamp__date=datetime.date(year,mon,day))
                return queryset
            except Exception as e:
                # print(e)
                messages.error(self.request,'Search error')
                return queryset
    def get_queryset(self):
        # 搜索
        if self.q:
            return self.check_q()
        # 快速选择记录类型
        history_type = self.history_type
        if history_type == 'today':
            return UserActivity.objects.today(user=self.request.user)
        if history_type == 'yesterday':
            return UserActivity.objects.yesterday(user=self.request.user)
        if history_type == 'aweek':
            return UserActivity.objects.within_week(user=self.request.user)
        return UserActivity.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        page_obj = context.get('page_obj',None) # 获取page对象
        # 填充上下文context
        context['history_type'] = self.get_history_type()
        context['history_type_dict'] = {'today':'今天','yesterday':'昨天','aweek':'一周内'}
        context['title'] = '历史记录'
        context['current_page_round'] = current_page_round(page_obj)
        return context

src/time_clock/templates/time_clock/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0048)https://v4.bootcss.com/docs/4.0/examples/cover/# -->
<html lang="zh-cn"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'time_clock/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'time_clock/css/cover.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    {% block content %}

    {% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'time_clock/js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'time_clock/js/popper.min.js' %}"></script>
    <script src="{% static 'time_clock/js/bootstrap.min.js' %}"></script>
  

</body>
</html>

src/time_clock/templates/time_clock/footer.html
<div class="inner">
        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
</div>

src/time_clock/templates/time_clock/history-pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <!-- 上一页 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
        </li>
        {% endif %}
        <!-- 当前附近页码 -->
        {% for page_num in current_page_round %}
        <li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
            <a class="page-link" {% if not page_num == '...' %} href="?page={{ page_num }}"{% endif %}>{{ page_num }}</a>
        </li>
        {% endfor %}
        <!-- 下一页 -->
        {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
        </li>
        {% endif %}
    </ul>
</nav>

src/time_clock/templates/time_clock/history-search.html
<form class="form-inline justify-content-center" style="margin-bottom: 1rem;" method="get">
    <input class="form-control mr-sm-2" name="datetime" style="width: 50%;"type="search" placeholder="格式：年-月-日" aria-label="Search" value="{{ request.GET.datetime }}">
    <button class="btn btn-outline-success btn-sm my-2 my-sm-0"style="margin-left: 0.3rem;" type="submit">Search</button>
    <div class="btn-group" style="padding-left: 0.5rem;"role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle btn-sm float-right" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ history_type }}
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
          <a class="dropdown-item" href="{% url 'time_clock:history' %}">全部</a>
          {% for datetype,value in history_type_dict.items %}
          <a class="dropdown-item" href="{% url 'time_clock:history-type' datetype %}">{{ value }}</a>
          {% endfor %}
        </div>
    </div>
</form>

src/time_clock/templates/time_clock/history-table.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Update</th>
        <th scope="col">Activity</th>
      </tr>
    </thead>
    <tbody>
      {% for user_activity in user_activity_list %}
      <tr>
        <th scope="row">{{ user_activity.activity_count }}</th>
        <td>{{ user_activity.user.username }}</td>
        <td>{{ user_activity.timestamp }}</td>
        <td>{{ user_activity.current_activity_display }}</td>
      </tr>
      {% empty %}
      无记录
      {% endfor %}
    </tbody>
</table>

src/time_clock/templates/time_clock/history.html
{% extends 'time_clock/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include 'time_clock/menu.html'%}
            
        </header>
        
        <main role="main" class="inner cover">
            {% include 'time_clock/messages.html'%}            
            {% include 'time_clock/history-search.html'%}       
            {% include 'time_clock/history-table.html'%}
        </main>
  
        <footer class="mastfoot mt-auto">
            {% include 'time_clock/history-pagination.html'%}
            {% include 'time_clock/footer.html'%}
        </footer>
 </div>
{% endblock %}

src/time_clock/templates/time_clock/index.html
{% extends 'time_clock/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include 'time_clock/menu.html'%}
        </header>
        
        <main role="main" class="inner cover">
            {% include 'time_clock/messages.html'%}
            {% include 'time_clock/main.html'%}
        </main>
  
        <footer class="mastfoot mt-auto">
            {% include 'time_clock/footer.html'%}
        </footer>
 </div>
{% endblock %}

src/time_clock/templates/time_clock/main.html
<h1 class="cover-heading">User Activity.</h1>
<p class="lead">当前状态:
    {% if recent_obj != None %}
    已{{ recent_obj.current_activity_display }}
    {% else %}
    无记录
    {% endif %}
 </p>
 <p class="lead">更新于:
        {% if recent_obj != None %}
        {{ recent_obj.timestamp }}
        {% else %}
        无记录
        {% endif %}
     </p>
<form method="post" action="">
{% csrf_token %}
<p class="lead">
    {% if form %}
    {% for field in form %}
    {{ field }}
    {% endfor %}
    {% endif %}
    <p class="text-danger">{{ form.non_field_errors.as_text }}</p>
    {% if recent_obj != None %}
    <input class="btn btn-lg btn-secondary" type="submit" value="{{ recent_obj.next_activity }}">
    {% elif request.user.is_authenticated == False %}
    <a class="btn btn-lg btn-secondary" href="{% url 'user:login' %}">请先登陆</a>
    {% else %}
    <input class="btn btn-lg btn-secondary" type="submit" value="签到">
    {% endif %}
</p>
</form>

src/time_clock/templates/time_clock/menu.html
<div class="inner">
        <h4 class="masthead-brand">{% if request.user.is_active %}{{ request.user.username }} {% else %} UserActivity{% endif %}</h4>
        <nav class="nav nav-masthead justify-content-center" style="padding-left:20px">
          <a class="nav-link {% if title == '打卡' %} active {% endif %}" href="{% url 'time_clock:index' %}">Home</a>
          {% if request.user.is_active %}
          <a class="nav-link active_logout" href="{% url 'user:logout' %}">Logout</a>
          {% else %}
          <a class="nav-link active_login" href="{% url 'user:login' %}">Login</a>
          {% endif %}
          <a class="nav-link {% if title == '历史记录' %} active {% endif %}" href="{% url 'time_clock:history' %}">History</a>
          
        </nav>
       
</div>

src/time_clock/templates/time_clock/messages.html
{% if messages %}
{% for message in messages %}
<div class="lead">
{% if message.tags %}
<p class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" >{{message}}</p>
{% endif %}
</div>
 {% endfor %}
 {% endif %}