src/checktime/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('index/',include('time_clock.urls')),
    path('',include('time_clock.urls')),
    path('user/',include('user.urls'))
]

src/user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('login/', views.Login_View.as_view(),name='login'),
    path('signup/', views.Signup_View.as_view(),name='signup'),
    path('logout/', views.auth_logout,name='logout')
]

src/user/models.py
from django.db import models

# Create your models here.

src/user/forms.py
import re
from django import forms 
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(label='账号',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'输入账号','required':'true'}))
    password = forms.CharField(label='密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'输入密码','type':'password','required':'true'}))

    def clean(self,*args,**kwagrs):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username','')
        password = cleaned_data.get('password','')
        exist_user = User.objects.filter(username__iexact=username)
        message = '账号或者密码错误'
        # 不存在这个用户
        if not exist_user.exists() or exist_user.count() != 1:
            raise forms.ValidationError(message,code='invalid')
        # 存在这个用户但密码错误
        if exist_user.exists() and exist_user.count()==1:
            user = exist_user.first()
            check_password = user.check_password(password)
            if not check_password :
                raise forms.ValidationError(message,code='invalid')
        return cleaned_data

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='账号',
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'输入账号，不能含有中文','required':'true'})
        )
    password1 = forms.CharField(
        label="密码",
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder':'输入密码,包含字母+数字组合，不少于8位','type':'password','required':'true'}),
    )
    password2 = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(attrs={'placeholder':'再次输入密码','type':'password','required':'true'}),
        strip=False,
        # help_text=_("Enter the same password as before, for verification."),
    )
    def clean_username(self):
        username = self.cleaned_data.get("username")
        zh_pattern = re.compile(u'[\u4e00-\u9fa5]+')
        result = zh_pattern.search(username)
        if result:
            raise forms.ValidationError(('账号不能含有中文'),code = 'invalid')
        return username

src/user/views.py
from django.contrib.auth import login,logout,authenticate
from django.shortcuts import render,redirect
from django.views import View
from .forms import LoginForm
from django.contrib import messages
from django.conf import settings
from .forms import SignupForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
# Create your views here.
def login_required(request):
    '''
    需要登陆访问
    根据/?next=,登陆跳转
    '''
    home_page_urlname = 'time_clock:index'
    get_full_path = request.get_full_path()
    try:
        if '?next=' in get_full_path : 
            get_full_urlnames = settings.NEXT_URLNAMES # 获取需要登陆的页面列表
            get_urlnames = [name.split(':') for name in get_full_urlnames] # 分开app_name和urlname
            index_next = get_full_path.find('next=') # 获取该索引位
            next_url = get_full_path[index_next:] # 获取next=到最后的字符
            get_url_name = next_url.split('/')[1] # 获取urlname
            # 只获取 urlname一致的list
            full_urlname_list = [fullname for fullname in get_urlnames if get_url_name == fullname[1]]
            one_full_onelist = full_urlname_list.pop() # 取消嵌套
            # 拼接成完整且唯一的url
            unique_url = '{appname}:{name}'.format(appname=one_full_onelist[0],name=one_full_onelist[1])
            return unique_url
    except Exception as e:
            print(e)
    return home_page_urlname

class Login_View(View):
    def get(self,request,*args,**kwargs):
        form = LoginForm()
        context = {}
        context['form'] = form
        context['title'] = '登陆'
        context['submit_text'] = 'Sign in'
        context['content_title'] = 'User Login'
        return render(request,'user/login.html',context)

    def post(self,request,*args,**kwargs):
        
        form = LoginForm(request.POST)
        context = {}
        context['form'] = form
        context['title'] = '登陆'
        context['submit_text'] = 'Sign in' 
        context['content_title'] = 'User Login' 
        if not form.is_valid():
            # 验证不通过，渲染同样模版
            return render(request, 'user/login.html',context)
        username = form.cleaned_data.get('username','')
        password = form.cleaned_data.get('password','')
        user = authenticate(username=username,password=password)
        if user.is_active:
            login(request,user)
            request.session['username'] = username
            messages.info(request, 'You Login Sucess')
            # 要求登陆
            get_next_urlname = login_required(self.request)
            if get_next_urlname:
                return redirect(get_next_urlname)
            return redirect('time_clock:index')       
        return render(request, 'user/login.html',context)
def auth_logout(request):
    logout(request)
    messages.success(request, 'You Logout Sucess')
    return redirect('user:login')
    
class Signup_View(CreateView):
    template_name = 'user/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('time_clock:index')

    def form_valid(self,form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        user = authenticate(username=cleaned_data['username'],
                            password=cleaned_data['password1'])
        
        login(self.request, user)
        messages.info(self.request, 'You are a frist Login Sucess')
        return result
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = '注册'
        context['submit_text'] = 'Register' 
        context['content_title'] = 'User Signup' 
        return context
        

src/user/templates/user/form.html
{% load crispy_forms_tags %}
<form method="POST" class="form-signin" action="">
        {% csrf_token %}
        <h1 class="cover-heading mb-4">{{content_title}}</h1>
        {% for field in form %}
        <div class="form-label-group mb-3">
            {{ field|as_crispy_field }}
        </div>
        {% endfor %}
        <p class="text-danger">{{ form.non_field_errors.as_text }}</p>
        {% if title == '登陆' %} 
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        {% endif %}
        <input class="btn btn-lg btn-primary btn-block" value="{{submit_text}}" type="submit">
        {% if title == '登陆' %}
        <a class="btn btn-lg btn-info btn-block" href="{% url 'user:signup' %}">No account ? Sign up</a>
        {% endif %}
        <!-- <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p> -->
</form>

src/user/templates/user/login.html
{% extends 'time_clock/base.html' %}


{% block title %}
{{title}}
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include 'time_clock/menu.html'%}
        </header>
  
        <main role="main" class="inner cover">
            {% include 'time_clock/messages.html'%}
            {% include 'user/form.html'%}
        </main>
  
        <footer class="mastfoot mt-auto">
            {% include 'time_clock/footer.html'%}
        </footer>
 </div>
{% endblock %}

src/user/templates/user/signup.html
{% extends 'time_clock/base.html' %}


{% block title %}
{{title}}
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include 'time_clock/menu.html'%}
        </header>
  
        <main role="main" class="inner cover">
            {% include 'time_clock/messages.html'%}
            {% include 'user/form.html'%}
        </main>
  
        <footer class="mastfoot mt-auto">
            {% include 'time_clock/footer.html'%}
        </footer>
 </div>
{% endblock %}